import { Material, Testimonial } from './types';

export const COURSES: Material[] = [
  // Editing
  {
    id: 'editing-vfx',
    title: 'VFX Master Pack',
    description: 'High-quality visual effects, overlays, and compositing assets for professional video editing.',
    category: 'editing',
    section: 'VFX Master Pack',
    thumbnail_icon: '💥',
    gradient: 'from-[#ff6b6b] to-[#f5c842]',
    is_free: true,
    resource_url: '#',
  },
  {
    id: 'editing-sfx',
    title: 'Ultimate SFX Library',
    description: '1000+ royalty-free sound effects, cinematic hits, risers, and ambient textures.',
    category: 'editing',
    section: 'Ultimate SFX Library',
    thumbnail_icon: '🎵',
    gradient: 'from-[#6c63ff] to-[#ff6b6b]',
    is_free: true,
    resource_url: '#',
  },
  {
    id: 'editing-icons',
    title: 'Premium Icon Sets',
    description: 'Vector icons, animated icons, and social media badges for your creative projects.',
    category: 'editing',
    section: 'Premium Icon Sets',
    thumbnail_icon: '🎨',
    gradient: 'from-[#43e8d8] to-[#6c63ff]',
    is_free: true,
    resource_url: '#',
  },
  {
    id: 'editing-pngs',
    title: 'Transparent PNG Assets',
    description: 'Thousands of high-resolution transparent PNGs, cutouts, and design elements.',
    category: 'editing',
    section: 'Transparent PNG Assets',
    thumbnail_icon: '🖼️',
    gradient: 'from-[#f5c842] to-[#ff6b6b]',
    is_free: true,
    resource_url: '#',
  },
  {
    id: 'editing-stock-images',
    title: 'Stock Images Collection',
    description: 'Curated high-quality stock photos for backgrounds, thumbnails, and social media posts.',
    category: 'editing',
    section: 'Stock Images Collection',
    thumbnail_icon: '📸',
    gradient: 'from-[#ff6b6b] to-[#43e8d8]',
    is_free: true,
    resource_url: '#',
  },
  {
    id: 'editing-stock-videos',
    title: 'Stock Video Footage',
    description: '4K and HD stock footage, drone shots, and cinematic B-roll for your videos.',
    category: 'editing',
    section: 'Stock Video Footage',
    thumbnail_icon: '📹',
    gradient: 'from-[#6c63ff] to-[#f5c842]',
    is_free: true,
    resource_url: '#',
  },
  {
    id: 'editing-luts',
    title: 'Cinematic LUTs Pack',
    description: 'Professional color grading presets for Premiere Pro, DaVinci Resolve, and mobile editors.',
    category: 'editing',
    section: 'Cinematic LUTs Pack',
    thumbnail_icon: '🌈',
    gradient: 'from-[#43e8d8] to-[#6c63ff]',
    is_free: true,
    resource_url: '#',
  },

  // Software
  {
    id: 'software-1',
    title: 'PC Software Megapack',
    description: '100+ essential PC tools: cleaners, optimizers, media players, office suites — all free.',
    category: 'software',
    section: 'PC Software',
    thumbnail_icon: '🖥️',
    gradient: 'from-[#6c63ff] to-[#43e8d8]',
    is_free: true,
    resource_url: '#',
  },
  {
    id: 'software-2',
    title: 'Android Apps Collection',
    description: '50+ premium Android apps normally paid on Play Store — free direct downloads.',
    category: 'software',
    section: 'Mobile Apps',
    thumbnail_icon: '📲',
    gradient: 'from-[#43e8d8] to-[#ff6b6b]',
    is_free: true,
    resource_url: '#',
  },
  {
    id: 'software-3',
    title: 'iOS Apps Free List',
    description: 'Curated list of free premium iPhone & iPad apps with download guides.',
    category: 'software',
    section: 'Mobile Apps',
    thumbnail_icon: '🍎',
    gradient: 'from-[#ff6b6b] to-[#6c63ff]',
    is_free: true,
    resource_url: '#',
  },
  {
    id: 'software-4',
    title: 'Gaming Tools & Software',
    description: 'FPS boosters, game recorders, screen capture tools, and mod managers — free.',
    category: 'software',
    section: 'Gaming Tools',
    thumbnail_icon: '🎮',
    gradient: 'from-[#f5c842] to-[#6c63ff]',
    is_free: true,
    resource_url: '#',
  },

  // AI
  {
    id: 'ai-1',
    title: 'ChatGPT Complete Masterclass',
    description: 'From beginner to power user — prompt engineering, automation, and business use cases.',
    category: 'ai',
    section: 'ChatGPT',
    thumbnail_icon: '🧠',
    gradient: 'from-[#43e8d8] to-[#6c63ff]',
    is_free: true,
    resource_url: '#',
  },
  {
    id: 'ai-2',
    title: 'Midjourney & AI Art Course',
    description: 'Create stunning AI art with Midjourney, DALL·E, and Stable Diffusion. Full guide.',
    category: 'ai',
    section: 'Midjourney',
    thumbnail_icon: '🎨',
    gradient: 'from-[#6c63ff] to-[#f5c842]',
    is_free: true,
    resource_url: '#',
  },
  {
    id: 'ai-3',
    title: 'AI Video Creation Course',
    description: 'Generate AI videos with Runway ML, Sora, and Pika. The future of content creation.',
    category: 'ai',
    section: 'Runway ML',
    thumbnail_icon: '🎬',
    gradient: 'from-[#ff6b6b] to-[#43e8d8]',
    is_free: true,
    resource_url: '#',
  },

  // Others
  {
    id: 'others-1',
    title: 'Freelancing Masterclass',
    description: 'Start earning online — Upwork, Fiverr, client management & proposal writing.',
    category: 'others',
    section: 'Freelancing',
    thumbnail_icon: '💰',
    gradient: 'from-[#f5c842] to-[#6c63ff]',
    is_free: true,
    resource_url: '#',
  },
  {
    id: 'others-2',
    title: 'Web Design Course',
    description: 'HTML, CSS, responsive design, and landing page creation for complete beginners.',
    category: 'others',
    section: 'Web Design',
    thumbnail_icon: '🌐',
    gradient: 'from-[#ff6b6b] to-[#f5c842]',
    is_free: true,
    resource_url: '#',
  },
  {
    id: 'others-3',
    title: 'Digital Marketing Course',
    description: 'Instagram, YouTube, SEO, Google Ads — grow any brand to millions organically.',
    category: 'others',
    section: 'Digital Marketing',
    thumbnail_icon: '📣',
    gradient: 'from-[#43e8d8] to-[#6c63ff]',
    is_free: true,
    resource_url: '#',
  },
];

export const CATEGORIES_STRUCTURE: any = {
  editing: {
    title: 'Material for Editing',
    sections: {
      'VFX Master Pack': ['All', 'Vehicle', 'Weapon', 'Nature/Magical Powers', 'Glass', 'Break', '3D', 'Action Sequence', 'Fire'],
      'Ultimate SFX Library': ['All', 'Transitions', 'Riser', 'Impact Sci-Fi', 'Cinematic', 'Minimalistic'],
      'Premium Icons Sets': ['Social Media', 'Animated Emojis'],
      'Transparent PNGs': ['All', 'Standard PNG', 'Geometrical Shape', 'Isolated Assets'],
      'Stock Image Collection': ['Sensory', 'Nostalgia', 'Hyper Realistic', 'Authenticity'],
      'Stock Video Footage': ['All'],
      'Cinematic LUTs': ['All', 'Cinematic', 'Vintage', 'Conversion'],
      'Overlays': ['All', 'Film Grains', 'Paper Grunge', 'Fire', 'Vintage', 'Futuristic', 'Trending', 'Motion']
    }
  },
  software: {
    title: 'Software and Apps',
    devices: ['Mobile', 'Desktop'],
    types: ['Editing', 'Game', 'AI', 'Others']
  },
  ai: {
    title: 'AI Master Classes',
    sections: {}
  },
  others: {
    title: 'Others',
    sections: {}
  }
};

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Rahul Kumar',
    role: 'Video Editor, Mumbai',
    text: '"Shikhar PS completely changed how I edit videos. The free courses are honestly better than paid ones I\'ve tried. Absolutely incredible platform!"',
    stars: 5,
    avatar_text: 'RK',
    gradient: 'from-[#6c63ff] to-[#43e8d8]',
  },
  {
    id: '2',
    name: 'Priya Sharma',
    role: 'Freelancer, Delhi',
    text: '"I learned AI tools that helped me land my first freelance client — all for free. Shikhar PS is a blessing for students who can\'t afford expensive courses."',
    stars: 5,
    avatar_text: 'PS',
    gradient: 'from-[#ff6b6b] to-[#f5c842]',
  },
  {
    id: '3',
    name: 'Arjun Mehta',
    role: 'Designer, Pune',
    text: '"The software collection here is massive. I got tools I was paying monthly subscriptions for — all totally free and safe. 10/10 recommend."',
    stars: 5,
    avatar_text: 'AM',
    gradient: 'from-[#43e8d8] to-[#6c63ff]',
  },
];
